/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.util.regex.Pattern;
import java.text.SimpleDateFormat;
/**
 *
 * @author choww
 */
public class ModifyAppointment extends javax.swing.JFrame {

    /**
     * Creates new form ModifyAppointment
     */
    public ModifyAppointment() {
        initComponents();
        ICLabel.setVisible(false);
        ICTxt.setVisible(false);
        PassportLabel.setVisible(false);
        PassportTxt.setVisible(false);
        SearchBut.setVisible(false);
        NameTxt.setEditable(false);
        CitizenshipTxt.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VaccineType = new javax.swing.JComboBox<>();
        VaccineCentre = new javax.swing.JComboBox<>();
        AppointTime = new javax.swing.JComboBox<>();
        UpdateBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();
        AppointDateChooser = new com.toedter.calendar.JDateChooser();
        ICLabel = new javax.swing.JLabel();
        CitizenshipTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PassportLabel = new javax.swing.JLabel();
        PassportTxt = new javax.swing.JTextField();
        SearchBut = new javax.swing.JButton();
        ICTxt = new javax.swing.JTextField();
        CitizenshipChoice = new javax.swing.JComboBox<>();
        SelectBut = new javax.swing.JButton();
        NameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Modify Vaccine Appointment");

        jLabel3.setText("Vaccine Type");

        jLabel4.setText("Vaccine Centre");

        jLabel5.setText("Appointment Date ");

        jLabel6.setText("Appointment Time");

        VaccineType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "Sinovac", "AstraZeneca", "Sputnik V", "CanSinoBio" }));

        VaccineCentre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kuala Lumpur", "Bukit Jalil", "Shah Alam", "Sungai Buloh", "Subang Jaya" }));

        AppointTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900" }));

        UpdateBut.setText("Update");
        UpdateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButActionPerformed(evt);
            }
        });

        ExitBut.setText("Exit");
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });

        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        AppointDateChooser.setDateFormatString("dd/MM/yyyy");

        ICLabel.setText("NRIC");

        jLabel8.setText("Citizenship");

        PassportLabel.setText("Passport No.");

        SearchBut.setText("Search");
        SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButActionPerformed(evt);
            }
        });

        CitizenshipChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Citizen", "Non-Citizen" }));
        CitizenshipChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitizenshipChoiceActionPerformed(evt);
            }
        });

        SelectBut.setText("Select");
        SelectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BackBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CitizenshipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CitizenshipChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SelectBut))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ICLabel)
                                                .addComponent(jLabel7))
                                            .addGap(95, 95, 95)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(NameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                                .addComponent(ICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PassportTxt)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(VaccineType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(VaccineCentre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(AppointDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(AppointTime, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(PassportLabel)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(SearchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(ExitBut)))))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CitizenshipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CitizenshipChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectBut))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ICLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PassportLabel)
                            .addComponent(PassportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(SearchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VaccineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VaccineCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AppointDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AppointTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ExitBut, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BackBut))
                    .addComponent(UpdateBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        this.setVisible(false);
        VaccineAppoint va = new VaccineAppoint();
        va.setVisible(true);
    }//GEN-LAST:event_BackButActionPerformed

    private void SearchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButActionPerformed
        String citizenship = CitizenshipTxt.getText();
        int flag=0;
        if(citizenship.equals("Citizen"))
        {
            try
            {
                File fpeople = new File("PeopleCitizen.txt");
                Scanner s = new Scanner(fpeople);
                String IC = ICTxt.getText();
                while(s.hasNext())
                {
                    String details = s.nextLine();
                    String[] info = details.split(",");
                    if(info[1].equals(IC))
                    {
                        NameTxt.setText(info[0]);
                        flag =1;
                        break;
                    }
                }
                if(flag==0)
                {
                    JOptionPane.showMessageDialog(this,"People not yet registered","Details not found",JOptionPane.INFORMATION_MESSAGE);
                    ICTxt.setText("");
                }

                File fappoint = new File("CitizenAppoint.txt");
                Scanner sf = new Scanner(fappoint);
                while(sf.hasNext())
                {
                    String appointdetails = sf.nextLine();
                    String[] appointinfo= appointdetails.split(",");
                    if(appointinfo[1].equals(IC))
                    {
                        Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(appointinfo[2]);  
                        AppointDateChooser.setDate(date1);
                        AppointTime.setSelectedItem(appointinfo[3]);
                        VaccineType.setSelectedItem(appointinfo[4]);
                        VaccineCentre.setSelectedItem(appointinfo[5]);
                        flag =1;
                        break;
                    }
                    else
                    {
                        flag=2;
                    }
                }
                if(flag==2)
                {
                    JOptionPane.showMessageDialog(this,"People not yet registered for vaccination yet","Registration Record not found",JOptionPane.INFORMATION_MESSAGE);
                    ICTxt.setText("");
                }
            }
            catch(FileNotFoundException fe)
            {
              JOptionPane.showMessageDialog(this,"File records not found","File error",JOptionPane.WARNING_MESSAGE);
            }
            catch(Exception e)
            {
                System.out.println("Error");
            }

        }
        else
        {
            try
            {
                File fpeople = new File("PeopleNonCitizen.txt");
                Scanner s = new Scanner(fpeople);
                String passport = PassportTxt.getText();
                while(s.hasNext())
                {
                    String details = s.nextLine();
                    String[] info = details.split(",");
                    if(info[1].equals(passport))
                    {
                        NameTxt.setText(info[0]);
                        flag =1;
                        break;
                    }
                }
                if(flag==0)
                {
                    JOptionPane.showMessageDialog(this,"People not yet registered","Details not found",JOptionPane.INFORMATION_MESSAGE);
                    PassportTxt.setText("");
                }

                File fappoint = new File("NonCitizenAppoint.txt");
                Scanner sf = new Scanner(fappoint);
                while(sf.hasNext())
                {
                    String appointdetails = sf.nextLine();
                    String[] appointinfo= appointdetails.split(",");
                    if(appointinfo[1].equals(passport))
                    {
                        Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(appointinfo[2]);  
                        AppointDateChooser.setDate(date1);
                        AppointTime.setSelectedItem(appointinfo[3]);
                        VaccineType.setSelectedItem(appointinfo[4]);
                        VaccineCentre.setSelectedItem(appointinfo[5]);
                        flag =1;
                        break;
                    }
                    else
                    {
                        flag=2;
                    }
                }
                if(flag==2)
                {
                    JOptionPane.showMessageDialog(this,"People not yet registered for vaccination yet","Registration Record not found",JOptionPane.INFORMATION_MESSAGE);
                    PassportTxt.setText("");
                }
            }
            catch(FileNotFoundException fe)
            {
              JOptionPane.showMessageDialog(this,"File records not found","File error",JOptionPane.WARNING_MESSAGE);
            }
            catch(Exception e)
            {
                System.out.println("Error");
            }
        }
    }//GEN-LAST:event_SearchButActionPerformed

    private void CitizenshipChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitizenshipChoiceActionPerformed

    }//GEN-LAST:event_CitizenshipChoiceActionPerformed

    private void SelectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButActionPerformed
        String citizenship = CitizenshipChoice.getSelectedItem().toString();
        CitizenshipTxt.setText(citizenship);
        SearchBut.setVisible(true);
        if(citizenship.equals("Citizen"))
        {
            ICLabel.setVisible(true);
            ICTxt.setVisible(true);
            ICTxt.revalidate();
            ICTxt.repaint();
            PassportTxt.setVisible(false);
            PassportLabel.setVisible(false);
        }
        else if(citizenship.equals("Non-Citizen"))
        {
            PassportLabel.setVisible(true);
            PassportTxt.setVisible(true);
            PassportTxt.revalidate();
            PassportTxt.repaint();
            ICLabel.setVisible(false);
            ICTxt.setVisible(false);
        }
    }//GEN-LAST:event_SelectButActionPerformed

    private void UpdateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButActionPerformed
        String citizenship = CitizenshipTxt.getText();
        String name = NameTxt.getText().trim();
        String IC = ICTxt.getText().trim();
        String passport = PassportTxt.getText().trim();
        String type = VaccineType.getSelectedItem().toString();
        String centre = VaccineCentre.getSelectedItem().toString();
        String date = ((JTextField)AppointDateChooser.getDateEditor().getUiComponent()).getText();
        String time = AppointTime.getSelectedItem().toString();
        try
        {
            if(citizenship.equals("Citizen"))
            {
                if(name.equals("") || type.equals("") || centre.equals("") || date.equals("") || time.equals(""))
                        JOptionPane.showMessageDialog(this,"kindly select dedtails to be modified","Nothing is selected",JOptionPane.INFORMATION_MESSAGE);
                else
                {
                    try
                    {
                        File fpeople = new File("CitizenAppoint.txt");
                        Scanner s = new Scanner(fpeople);
                        StringBuilder buffer = new StringBuilder();
                            
                        while(s.hasNext())
                        {
                            String details = s.nextLine();   
                            if(details.contains(IC))
                            {
                                String linetochange = details;
                                // searches a string for a specified character, and returns a new string where the specified character(s) are replaced.
                                linetochange = linetochange.replace(details,name+","+IC+","+date+","+time+","+type+","+centre);
                                buffer.append(linetochange+System.lineSeparator());
                            }
                            else
                                buffer.append(details+System.lineSeparator());
                        }
                        String filedetail = buffer.toString();
                        FileWriter fw = new FileWriter(fpeople);
                        fw.write(filedetail);
                        fw.close();
                        CitizenshipTxt.setText("");
                        NameTxt.setText("");
                        ICTxt.setText("");
                        AppointDateChooser.setCalendar(null);
                        JOptionPane.showMessageDialog(this,"Record Successfully Modified","Record removed",JOptionPane.INFORMATION_MESSAGE);
                            
                    }
                    catch(IOException io)
                    {
                        System.out.println("IO error"); // Validation
                    }
                }
            }
            else
            {
                if(name.equals("") || type.equals("") || centre.equals("") || date.equals("") || time.equals(""))
                        JOptionPane.showMessageDialog(this,"kindly select dedtails to be modified","Nothing is selected",JOptionPane.INFORMATION_MESSAGE);
                else
                {
                    try
                    {
                        File fpeople = new File("NonCitizenAppoint.txt");
                        Scanner s = new Scanner(fpeople);
                        StringBuilder buffer = new StringBuilder();
                            
                        while(s.hasNext()) // Go through lines
                        {
                            String details = s.nextLine();   
                            if(details.contains(passport))
                            {
                                String linetochange = details;
                                // searches a string for a specified character, and returns a new string where the specified character(s) are replaced.
                                linetochange = linetochange.replace(details,name+","+passport+","+date+","+time+","+type+","+centre);
                                buffer.append(linetochange+System.lineSeparator());
                            }
                            else
                                buffer.append(details+System.lineSeparator());
                        }
                        String filedetail = buffer.toString();
                        FileWriter fw = new FileWriter(fpeople);
                        fw.write(filedetail);
                        fw.close();
                        CitizenshipTxt.setText("");
                        NameTxt.setText("");
                        ICTxt.setText("");
                        AppointDateChooser.setCalendar(null);
                        JOptionPane.showMessageDialog(this,"Record Successfully Modified","Record removed",JOptionPane.INFORMATION_MESSAGE);
                            
                    }
                    catch(IOException io)
                    {
                        System.out.println("IO error"); // Validation
                    }
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Error");        // Validation
        }
        finally
        {
            ICLabel.setVisible(false);
            ICTxt.setVisible(false);
            PassportTxt.setVisible(false);
            PassportLabel.setVisible(false);
            SearchBut.setVisible(false);
        }
    }//GEN-LAST:event_UpdateButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser AppointDateChooser;
    private javax.swing.JComboBox<String> AppointTime;
    private javax.swing.JButton BackBut;
    private javax.swing.JComboBox<String> CitizenshipChoice;
    private javax.swing.JTextField CitizenshipTxt;
    private javax.swing.JButton ExitBut;
    private javax.swing.JLabel ICLabel;
    private javax.swing.JTextField ICTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PassportLabel;
    private javax.swing.JTextField PassportTxt;
    private javax.swing.JButton SearchBut;
    private javax.swing.JButton SelectBut;
    private javax.swing.JButton UpdateBut;
    private javax.swing.JComboBox<String> VaccineCentre;
    private javax.swing.JComboBox<String> VaccineType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
