/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import java.io.*;
import java.util.*;
import java.util.regex.Pattern;

/**
 *
 * @author choww
 */
public class SearchSupplyVaccineCentre_VaccineWise extends javax.swing.JFrame {

    /**
     * Creates new form SearchSupplyVaccineCentreWise
     */
    public SearchSupplyVaccineCentre_VaccineWise() {
        initComponents();
        VaccineChoice.setVisible(false);
        CentreChoice.setVisible(false);
        SearchBut.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewTxt = new javax.swing.JTextArea();
        BackBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        SearchChoice = new javax.swing.JComboBox<>();
        SelectBut = new javax.swing.JButton();
        VaccineChoice = new javax.swing.JComboBox<>();
        CentreChoice = new javax.swing.JComboBox<>();
        SearchBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search Supply Vaccine Record ");

        ViewTxt.setColumns(20);
        ViewTxt.setRows(5);
        jScrollPane1.setViewportView(ViewTxt);

        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        ExitBut.setText("Exit");
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });

        SearchChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centre Wise", "Vaccine Wise" }));

        SelectBut.setText("Select");
        SelectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButActionPerformed(evt);
            }
        });

        VaccineChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "Sinovac", "AstraZeneca", "Sputnik V", "CanSinoBio" }));

        CentreChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kuala Lumpur", "Bukit Jalil", "Shah Alam", "Sungai Buloh", "Subang Jaya" }));

        SearchBut.setText("Search");
        SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitBut)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CentreChoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VaccineChoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchChoice, 0, 139, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectBut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectBut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(VaccineChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CentreChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(SearchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBut)
                    .addComponent(ExitBut))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
       this.setVisible(false);
       SearchSupplyVaccine ssv = new SearchSupplyVaccine();
       ssv.setVisible(true);
    }//GEN-LAST:event_BackButActionPerformed

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ExitButActionPerformed

    private void SelectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButActionPerformed
        String choice = SearchChoice.getSelectedItem().toString();
        try
        {
            if(choice.equals("Centre Wise"))
            {
                CentreChoice.setVisible(true);
                SearchBut.setVisible(true);
                VaccineChoice.setVisible(false);
            }
            else
            {
                VaccineChoice.setVisible(true);
                SearchBut.setVisible(true);
                CentreChoice.setVisible(false);
            }
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_SelectButActionPerformed

    private void SearchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButActionPerformed
        String choice = SearchChoice.getSelectedItem().toString();
        try
        {
            File fs = new File("SupplyVaccine.txt");
            Scanner s = new Scanner(fs);
            ViewTxt.setText("");
            if(choice.equals("Centre Wise"))
            {
                String centrechoice = CentreChoice.getSelectedItem().toString();
                switch(centrechoice)
                {
                    case "Kuala Lumpur":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[2].equals(centrechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[1],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "Bukit Jalil":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[2].equals(centrechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[1],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "Shah Alam":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[2].equals(centrechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[1],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "Sungai Buloh":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[2].equals(centrechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[1],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "Subang Jaya":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[2].equals(centrechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[1],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                }
            }
            else
            {
                String vaccinechoice = VaccineChoice.getSelectedItem().toString();
                switch(vaccinechoice)
                {
                    case "Pfizer":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[1].equals(vaccinechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[2],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "Sinovac":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[1].equals(vaccinechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[2],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "AstraZeneca":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[1].equals(vaccinechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[2],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "CanSinoBio":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[1].equals(vaccinechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[2],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                    case "Sputnik V":
                    {
                        while(s.hasNext())
                        {
                            String details = s.nextLine();
                            String[] info = details.split(",");
                            if(info[1].equals(vaccinechoice))
                            {
                                String formatted = String.format("%1$-8s %2$-15s %3$-10s %4$-15s\n",info[0],info[2],info[3],info[4]);
                                ViewTxt.append(formatted);
                            }
                        }
                        break;
                    }
                }
            }
        }
        catch(FileNotFoundException fe)
        {
            JOptionPane.showMessageDialog(this,"File records not found","File error",JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e)
        {
            System.out.println("error");
        }
    }//GEN-LAST:event_SearchButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchSupplyVaccineCentre_VaccineWise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchSupplyVaccineCentre_VaccineWise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchSupplyVaccineCentre_VaccineWise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchSupplyVaccineCentre_VaccineWise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchSupplyVaccineCentre_VaccineWise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JComboBox<String> CentreChoice;
    private javax.swing.JButton ExitBut;
    private javax.swing.JButton SearchBut;
    private javax.swing.JComboBox<String> SearchChoice;
    private javax.swing.JButton SelectBut;
    private javax.swing.JComboBox<String> VaccineChoice;
    private javax.swing.JTextArea ViewTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
